wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1717506448.380429
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 103
      - 105
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 103
      - 105
      3:
      - 23
      4: 3.11.8
      5: 0.16.2
      6: 4.38.2
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
